[versions]
agp = "8.13.0"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.11.00"
material3 = "1.4.0"
credentials = "1.5.0"
media3 = "1.8.0"
media3-ui = "1.8.0"
media3-common = "1.8.0"
datastore = "1.1.7"
coil = "2.7.0"
googleid = "1.1.1"
composeMaterial = "1.7.8"
firebaseBom = "34.5.0"
ggl-services = "4.4.4"
firebaseDatabase = "21.0.0"
firebaseAuth = "23.2.1"
navHost = "2.9.6"
media3-hls = "1.8.0"
media3-session = "1.8.0"
paging = "3.4.0-alpha04"
paging-runtime = "3.4.0-alpha04"
paging-runtime-ktx = "3.4.0-alpha04"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
androidx-credentials-auth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3-ui" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3-common" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
compose-materials = { module = "androidx.compose.material:material-icons-extended", version.ref = "composeMaterial" }
google-firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom"}
google-firebase-database = { module = "com.google.firebase:firebase-database-ktx", version.ref = "firebaseDatabase"}
google-firebase-auth = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuth" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navHost" }
androidx-media3-hls = { module = "androidx.media3:media3-exoplayer-hls", version.ref = "media3-hls" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime", version.ref = "paging-runtime" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging-runtime-ktx" }
androidx-media3-session = { module = "androidx.media3:media3-session", version.ref = "media3-session" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "ggl-services" }

